import { useEffect, useState } from 'react'
import type { RoomState } from '@/types/workshop'
import type { RoomConnection } from '@/lib/partykit'
import { SparkleIcon } from '@phosphor-icons/react'
import { Button } from '../button'

type AISummaryProps = {
  room: RoomState
  connection: RoomConnection
  isAdmin: boolean
}

export function AISummary({ room, connection, isAdmin }: AISummaryProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  useEffect(() => {
    // Auto-generate summary on mount if not exists or if stale (admin only)
    if (!isAdmin) return

    if (!room.aiSummary) {
      handleGenerate()
    } else {
      // Check if summary is stale (older than last vote)
      const lastVoteTimestamp = Math.max(
        ...room.cards.flatMap((card) =>
          card.votes.map((vote) => vote.timestamp),
        ),
        0,
      )

      if (lastVoteTimestamp > room.aiSummary.generatedAt) {
        handleGenerate()
      }
    }
  }, [])

  const handleGenerate = () => {
    setIsGenerating(true)
    connection.generateAISummary()

    // Reset loading state after a reasonable timeout
    setTimeout(() => {
      setIsGenerating(false)
    }, 10000)
  }

  // Reset loading state when summary arrives
  useEffect(() => {
    if (room.aiSummary && isGenerating) {
      setIsGenerating(false)
    }
  }, [room.aiSummary])

  if (isGenerating && !room.aiSummary) {
    return (
      <div>
        <div className="flex items-center gap-1 mb-4">
          <SparkleIcon size={24} className="text-purple-600 animate-pulse" />
          <h3 className="text-lg font-medium">AI Summary</h3>
        </div>
        <div className="bg-white border border-border p-6">
          <div className="flex items-center gap-3">
            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-purple-600"></div>
            <p className="text-gray-600">Generating AI insights...</p>
          </div>
        </div>
      </div>
    )
  }

  if (!room.aiSummary) {
    return (
      <div>
        <div className="flex items-center gap-2 mb-4">
          <SparkleIcon size={24} className="text-purple-600" />
          <h3 className="text-lg font-medium">AI Summary</h3>
        </div>
        <div className="bg-white border border-border p-6">
          <p className="text-gray-600 mb-4">
            {isAdmin
              ? 'No AI summary available yet.'
              : 'AI summary will be generated by the facilitator.'}
          </p>
          {isAdmin && (
            <Button
              onClick={handleGenerate}
              className="bg-purple-600 hover:bg-purple-700"
            >
              Generate Summary
            </Button>
          )}
        </div>
      </div>
    )
  }

  const { keyInsights, aiSuggestions, wordCloud, generatedAt } = room.aiSummary

  return (
    <div>
      <div className="flex gap-2 items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <SparkleIcon size={24} className="text-purple-600" />
          <h3 className="text-lg font-medium">AI Summary</h3>
        </div>
        <div className="flex flex-col items-end gap-1">
          {isAdmin && (
            <Button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="bg-purple-600 hover:bg-purple-700 text-xs px-2 py-1"
            >
              {isGenerating ? 'Regenerating...' : 'Regenerate'}
            </Button>
          )}
        </div>
      </div>

      <div className="space-y-3">
        {/* Word Cloud */}
        {wordCloud && wordCloud.length > 0 && (
          <div className="border-border border px-3 py-2">
            <h4 className="font-medium mb-2">Key Topics</h4>
            <div className="flex flex-wrap gap-2 items-center justify-center text-center">
              {[...wordCloud]
                .sort((a, b) => b.weight - a.weight)
                .map((item, index) => {
                  // Calculate font size based on weight (1-10 -> 1rem-3rem)
                  const fontSize = 1 + (item.weight / 15)

                  return (
                    <span
                      key={index}
                      className="font-medium cursor-default select-none leading-tighter"
                      style={{
                        fontSize: `${fontSize}rem`,
                        lineHeight: 1,
                      }}
                      title={`Weight: ${item.weight}/10`}
                    >
                      {item.topic}
                    </span>
                  )
                })}
            </div>
          </div>
        )}

        {/* Key Insights */}
        <div className="border-border border px-3 py-2">
          <h4 className="font-medium mb-2">Key Insights</h4>
          {keyInsights.length > 0 ? (
            <ul className="space-y-2">
              {keyInsights.map((insight, index) => (
                <li key={index} className="flex gap-2 text-sm">
                  <span className="font-medium mt-0.5">•</span>
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">No insights available</p>
          )}
        </div>

        {/* AI Suggestions */}
        <div className="border-border border px-3 py-2">
          <h4 className="font-medium mb-2">Suggestions</h4>
          {aiSuggestions.length > 0 ? (
            <ul className="space-y-2">
              {aiSuggestions.map((suggestion, index) => (
                <li key={index} className="flex gap-2 text-sm">
                  <span className="font-medium mt-0.5">•</span>
                  <span>{suggestion}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-gray-500">No suggestions available</p>
          )}
        </div>
      </div>
    </div>
  )
}

function getTimeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000)

  if (seconds < 60) return 'just now'
  if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes ago`
  if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`
  return `${Math.floor(seconds / 86400)} days ago`
}
