import { useEffect, useState } from 'react'
import type { RoomState } from '@/types/workshop'
import type { RoomConnection } from '@/lib/partykit'
import { SparkleIcon } from '@phosphor-icons/react'

type AISummaryProps = {
  room: RoomState
  connection: RoomConnection
  isAdmin: boolean
}

export function AISummary({ room, connection, isAdmin }: AISummaryProps) {
  const [isGenerating, setIsGenerating] = useState(false)

  useEffect(() => {
    // Auto-generate summary on mount if not exists or if stale (admin only)
    if (!isAdmin) return

    if (!room.aiSummary) {
      handleGenerate()
    } else {
      // Check if summary is stale (older than last vote)
      const lastVoteTimestamp = Math.max(
        ...room.cards.flatMap((card) =>
          card.votes.map((vote) => vote.timestamp),
        ),
        0,
      )

      if (lastVoteTimestamp > room.aiSummary.generatedAt) {
        handleGenerate()
      }
    }
  }, [])

  const handleGenerate = () => {
    setIsGenerating(true)
    connection.generateAISummary()

    // Reset loading state after a reasonable timeout
    setTimeout(() => {
      setIsGenerating(false)
    }, 10000)
  }

  // Reset loading state when summary arrives
  useEffect(() => {
    if (room.aiSummary && isGenerating) {
      setIsGenerating(false)
    }
  }, [room.aiSummary])

  if (isGenerating && !room.aiSummary) {
    return (
      <div className="mt-8">
        <div className="flex items-center gap-1 mb-4">
          <SparkleIcon size={24} className="text-purple-600 animate-pulse" />
          <h3 className="text-lg font-semibold">AI Summary</h3>
        </div>
        <div className="bg-white border border-gray-200 p-6">
          <div className="flex items-center gap-3">
            <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-purple-600"></div>
            <p className="text-gray-600">Generating AI insights...</p>
          </div>
        </div>
      </div>
    )
  }

  if (!room.aiSummary) {
    return (
      <div className="mt-8">
        <div className="flex items-center gap-2 mb-4">
          <SparkleIcon size={24} className="text-purple-600" />
          <h3 className="text-lg font-semibold">AI Summary</h3>
        </div>
        <div className="bg-white border border-gray-200 p-6">
          <p className="text-gray-600 mb-4">
            {isAdmin
              ? 'No AI summary available yet.'
              : 'AI summary will be generated by the facilitator.'}
          </p>
          {isAdmin && (
            <button
              onClick={handleGenerate}
              className="px-4 py-2 bg-purple-600 text-white rounded hover:bg-purple-700 transition-colors"
            >
              Generate Summary
            </button>
          )}
        </div>
      </div>
    )
  }

  const { keyInsights, aiSuggestions, generatedAt } = room.aiSummary
  const timeAgo = getTimeAgo(generatedAt)

  return (
    <div className="mt-8">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <SparkleIcon size={24} className="text-purple-600" />
          <h3 className="text-lg font-semibold">AI Summary</h3>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-gray-500">
            Generated {timeAgo}
          </span>
          {isAdmin && (
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="px-3 py-1.5 text-sm bg-purple-600 text-white rounded hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isGenerating ? 'Regenerating...' : 'Regenerate'}
            </button>
          )}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4">
        {/* Key Insights */}
        <div className="bg-gradient-to-br from-purple-50 to-blue-50 border border-purple-200 p-6">
          <h4 className="font-semibold text-purple-900 mb-3">Key Insights</h4>
          {keyInsights.length > 0 ? (
            <ul className="space-y-2">
              {keyInsights.map((insight, index) => (
                <li key={index} className="flex gap-2 text-sm text-gray-700">
                  <span className="text-purple-600 font-bold mt-0.5">•</span>
                  <span>{insight}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-gray-500">No insights available</p>
          )}
        </div>

        {/* AI Suggestions */}
        <div className="bg-gradient-to-br from-green-50 to-teal-50 border border-green-200 p-6">
          <h4 className="font-semibold text-green-900 mb-3">AI Suggestions</h4>
          {aiSuggestions.length > 0 ? (
            <ul className="space-y-2">
              {aiSuggestions.map((suggestion, index) => (
                <li key={index} className="flex gap-2 text-sm text-gray-700">
                  <span className="text-green-600 font-bold mt-0.5">•</span>
                  <span>{suggestion}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-gray-500">No suggestions available</p>
          )}
        </div>
      </div>
    </div>
  )
}

function getTimeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000)

  if (seconds < 60) return 'just now'
  if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes ago`
  if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`
  return `${Math.floor(seconds / 86400)} days ago`
}
